# Generated by Django 4.2.4 on 2023-08-31 21:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Escola')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefones')),
                ('email', models.EmailField(max_length=120, verbose_name='Email')),
                ('bairro', models.CharField(max_length=200, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=200, verbose_name='cidade')),
                ('rua', models.CharField(max_length=200, verbose_name='Rua')),
                ('logradouro', models.CharField(max_length=200, verbose_name='Logradouro')),
                ('cep', models.CharField(max_length=200, verbose_name='Endereço')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Responsaveis')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CFP')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefones')),
                ('foto', models.ImageField(upload_to='responsaveis/', verbose_name='Foto')),
                ('largura_desejada', models.PositiveIntegerField(verbose_name=720)),
                ('altura_desejada', models.PositiveIntegerField(verbose_name=720)),
                ('email', models.EmailField(max_length=120, verbose_name='Email')),
                ('bairro', models.CharField(max_length=200, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=200, verbose_name='cidade')),
                ('rua', models.CharField(max_length=200, verbose_name='Rua')),
                ('logradouro', models.CharField(max_length=200, verbose_name='Logradouro')),
                ('cep', models.CharField(max_length=200, verbose_name='Endereço')),
                ('escola', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='test_website.escola')),
            ],
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Visitante')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('foto', models.ImageField(upload_to='visitantes__autorizados/', verbose_name='Foto')),
                ('largura_desejada', models.PositiveIntegerField(verbose_name=720)),
                ('altura_desejada', models.PositiveIntegerField(verbose_name=720)),
                ('hora_ativacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Hora de ativaçao')),
                ('responsavel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='test_website.pais')),
            ],
        ),
        migrations.CreateModel(
            name='Filhos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('foto', models.ImageField(upload_to='visitantes__autorizados/', verbose_name='Foto')),
                ('largura_desejada', models.PositiveIntegerField(verbose_name=720)),
                ('altura_desejada', models.PositiveIntegerField(verbose_name=720)),
                ('responsavel', models.ManyToManyField(to='test_website.pais', verbose_name='Alunos')),
                ('visitante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='test_website.visitante')),
            ],
        ),
    ]
