# Generated by Django 4.2.4 on 2023-08-31 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_website', '0002_alter_escola_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='cep',
            field=models.CharField(max_length=200, verbose_name='Cep'),
        ),
    ]
