# Generated by Django 4.2.4 on 2023-08-31 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_website', '0005_remove_filhos_altura_desejada_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitante',
            old_name='hora_ativacao',
            new_name='data_cadastro',
        ),
    ]
